name: Merge-Tests
on:
  push:
    branches: [ master ]

env:
  KEY_HEADER: "X-API-KEY: tHyCZqoH2yap6fXheRYVg4F4RKSgEk6R11zZkLNy"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Reflect tests
        run: |
          curl -X POST \
            -H "$KEY_HEADER" \
            -H "Content-Type: application/json" \
            -d '{
              "gitHub": {
                "owner": "sankar7466",
                "repo": "Reflect",
                "sha": "'${{ github.event.pull_request.head.sha }}'"
              }
            }' \
            -s https://api.reflect.run/v1/suites/git-test/executions
